### ISSUE TITLE
Problems with Gmail

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [synox/void-mail#4]
What should be IMAP_SERVER for GMAIL.

Also after few seconds

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by synox** [comment]
Which settings did you use? See https://support.google.com/mail/answer/7126229?hl=en
What is in the error log?

**Comment by ParveenBhadooOfficial** [comment]
It worked with the imap.gmail.com and less secured apps enabled with passwords from app passwords.

Test Deploy at https://bhadoomail.herokuapp.com/

**Comment by synox** [comment]
Cool! Does it work for you?

**Comment by ParveenBhadooOfficial** [comment]
Does it cache's data. https://beta.bhadoomail.com/1@bhadoomail.com shows 5 emails even when they are deleted from gmail completely, and when we open them it says email not found.

**Comment by synox** [comment]
Yes it keeps them all. Delete is not implemented yet.

**Comment by ParveenBhadooOfficial** [comment]
Also emails doesn't shows as expected.

https://inbox.bhadoomail.com/?discussant@bhadoomail.com shows 1 email

https://beta.bhadoomail.com/discussant@bhadoomail.com shows none.

**Comment by synox** [comment]
After the restart it takes a while until all mails are loaded (it loads the newest first). Add the ENV Variable to see the debug output: 

    DEBUG=void-mail:*

Then you check if the initial load is complete.
